SetProtocol/set.js

package.json, src/api/ERC20API.ts, src/wrappers/set-protocol-v2/ERC20Wrapper.ts, test/api/ERC20API.spec.ts
* Allows the user to pass in a caller address to the ERC-20 API for checking allowances.
* Without this, logged-out allowance fetches from infura fail
=> Expose Caller Address in ERC-20 API

README.md
It looks like CircleCI badges generated via [these steps](https://circleci.com/docs/2.0/status-badges/#creating-badges-for-private-repositories96166267374796c653d736869656c64) don't render correctly in this README. My suspicion is that the `.` in set.js is a possible cause.
I generated a shield badge via https://shields.io/category/build and it works in the preview
=> Fix circleci badge (attempt 2)

package.json, yarn.lock
Moonquant noted in telegram a while ago that set.js is a huge dep and they were having difficulty spinning up a lamda instance with it. 
Believe this is due to unused Truffle dependencies in the package, have removed them here.
Also updating Web3 to latest. 
(PR supercedes #68)
=> Remove unused truffle dependencies / update Web3 to 1.5.2

package.json, src/api/DebtIssuanceAPI.ts, src/api/ERC20API.ts, src/api/SetTokenAPI.ts, src/wrappers/set-protocol-v2/ContractWrapper.ts, src/wrappers/set-protocol-v2/DebtIssuanceModuleWrapper.ts, src/wrappers/set-protocol-v2/ERC20Wrapper.ts, src/wrappers/set-protocol-v2/SetTokenCreatorWrapper.ts, test/api/DebtIssuanceAPI.spec.ts, test/api/ERC20API.spec.ts, test/api/SetTokenAPI.spec.ts, test/wrappers/set-protocol-v2/DebtIssuanceModuleWrapper.spec.ts, test/wrappers/set-protocol-v2/ERC20Wrapper.spec.ts, yarn.lock
Pulls in changes at [set-protocol-v2 PR 131][1] which upgrades ethers to 5.4.6 and uses a new typechain package
**Upgrades**
+ ethers -> 5.4.6
+ ganache-cli -> 6.12.2
+ typescript -> 4.4.2
+ set-protocol-v2 -> 0.1.0
**TODO**
Note: There are a handful of breaking TS interface changes here (coming from upstream at set-protocol-v2). When we publish we should bump the version to 0.3.0 
[1]: https://github.com/SetProtocol/set-protocol-v2/pull/131
=> Upgrade ethers to 5.4.6 / set-protocol-v2@0.1.0

package.json, src/Set.ts, src/api/DebtIssuanceV2API.ts, src/api/index.ts, src/types/common.ts, src/wrappers/set-protocol-v2/ContractWrapper.ts, src/wrappers/set-protocol-v2/DebtIssuanceModuleV2Wrapper.ts, test/api/DebtIssuanceV2API.spec.ts, test/wrappers/set-protocol-v2/DebtIssuanceModuleV2Wrapper.spec.ts, yarn.lock
Plus test cases (for accruing interest after blocks have passed) and package bump for updated set-protocol-v2 contract
=> Add API and Wrapper classes for DebtIssuanceModuleV2

src/wrappers/set-protocol-v2/ContractWrapper.ts, yarn.lock
Bump the set-protocol-v2 dependency in set.js and run install.
Add the factory for the upcoming SlippageIssuanceModule!
=> Bump set.js's v2 dependency and add SlippageIssuanceModule factory

src/api/SlippageIssuanceAPI.ts, src/wrappers/set-protocol-v2/SlippageIssuanceModuleWrapper.ts, test/wrappers/set-protocol-v2/SlippageIssuanceModuleWrapper.spec.ts
New Wrapper class within set.js to be able to abstract away the SlippageIssuanceModule interface.
Added unit tests for the new functions `issueWithSlippage` and `redeemWithSlippage`
=> Add SlippageIssuanceModuleWrapper class and tests

src/api/SlippageIssuanceAPI.ts, src/assertions/CommonAssertions.ts, test/api/SlippageIssuanceAPI.spec.ts
This class uses the Wrapper class in the earlier PR to interface with the new SlippageIssuanceModule contract.
The API can be used by clients such as the UI.
Add validation & tests to ensure that the issuance/redemption components are unique and equal length with the slippage amounts list.
=> Add SlippageIssuanceAPI class for clients to consume

package.json, src/Set.ts, src/api/index.ts, src/types/common.ts
Previously we checked in the API and Wrapper class. Now we add it to set.ts and index.ts to be properly consumed by downstream clients (missed this in the previous bump)
=> Add the SlippageIssuanceAPI to the Set.JS Index

package.json, src/wrappers/set-protocol-v2/SlippageIssuanceModuleWrapper.ts, yarn.lock
This PR is necessary to resolve set-ui reverts when fetching required issuance units for Perp Leverage tokens using the SIM.  
PR:
+ Updates set-protocol-v2 to v.0.1.8 which includes fixes to the SIM interface from [set-protocol-v2 PR 182][1]
+ Updates SIM wrapper logic to `callStatic` new non-view units getters
[1]: https://github.com/SetProtocol/set-protocol-v2/pull/182
=> Patch SIM issuance/redemption units getters

package.json, src/api/utils/gasOracle.ts
Prices are too high when viewed from a library client (e.g. set-ui when manually fetching for price instead of relying on native call).
=> Convert wei to gwei in Optimism gas fetcher

package.json, src/assertions/CommonAssertions.ts
Previously this did not allow for a false value
=> Fix isNotUndefined assertion

package.json, src/wrappers/set-protocol-v2/ContractWrapper.ts, src/wrappers/set-protocol-v2/PerpV2LeverageModuleWrapper.ts, yarn.lock
* Bump the set-protocol-v2 library in package.json
* Add the PerpV2LeverageModule factory into the Contract wrapper construct
* Create a PerpV2LeverageModuleWrapper class
Follow up PR will update the set.js config and add the API class/tests
Note - To deduplicate contract testing code I opted to rely on upcoming API tests to create expectations that contract instances are correct called via the Wrapper class. Including smart contract level tests within set.js seems to create redundant guarantees when the set-protocol-v2 repo should be the source of truth for implementation/tests.
=> Add PerpV2LeverageModule factory and Wrapper/tests

package.json, src/Set.ts, src/api/PerpV2LeverageAPI.ts, src/api/SlippageIssuanceAPI.ts, src/api/index.ts, src/types/common.ts, src/wrappers/set-protocol-v2/SlippageIssuanceModuleWrapper.ts, test/api/PerpV2LeverageAPI.spec.ts
Set.js version 0.4.9:
Includes the `PerpV2LeverageAPI` class to `Set`, and allows for library users to pass in a `perpV2LeverageModuleAddress` contract address into the config object.
With this, we can have access to getters such as `collateralToken` and `getAccountInfo` to monitor positional state with Perpetual Protocol.
=> Add PerpV2LeverageAPI and tests

.circleci/config.yml, package.json, src/Set.ts, src/api/PerpV2LeverageAPI.ts, src/api/PerpV2LeverageViewerAPI.ts, src/api/index.ts, src/types/common.ts, src/wrappers/set-protocol-v2/ContractWrapper.ts, src/wrappers/set-protocol-v2/PerpV2LeverageModuleViewerWrapper.ts, src/wrappers/set-protocol-v2/PerpV2LeverageModuleWrapper.ts, test/api/PerpV2LeverageViewerAPI.spec.ts, test/wrappers/set-protocol-v2/DebtIssuanceModuleV2Wrapper.spec.ts, test/wrappers/set-protocol-v2/SlippageIssuanceModuleWrapper.spec.ts, yarn.lock
New PerpV2LeverageViewerAPI for the upcoming contract that will abstract a lot of data getters out of the existing PerpV2LeverageModule.
Relevant smart contract PR: https://github.com/SetProtocol/set-protocol-v2/pull/185
=> Create new PerpV2LeverageViewerAPI for PerpModule Viewer contract

README.md
Updates the readme to make getting started easier.
* Links to mainnet, polygon, optimism deployed contract addresses
* Adds example getting started configuration.
=> Update Read Me with SetJs Configuration Links

.circleci/config.yml, package.json, scripts/init_chain_internal.sh, test/wrappers/set-protocol-v2/DebtIssuanceModuleV2Wrapper.spec.ts, test/wrappers/set-protocol-v2/ProtocolViewerWrapper.spec.ts, yarn.lock
PR:
+ adds a missing statement to the circle logic that splits tests between parallel containers. (Both containers were running all the tests)
+ upgrades [ganache to V7][3] (~3X faster than V6)
+ uses Node 12 container in CI (necessary for V7)
Cuts ~ 12 min (75%) from test job.
One consideration is whether upgrading the Node version here is ok. I *think* this is fine for set-ui since:
+ we already install with `--ignore-engines` over there (by default it's pinned to `10.13`)  
+ it's only for a dev dependency
**Benchmarks**
| Branch |  Test Time |
|----|----|
| master | [17m 6s][1] |
| PR | [4m 53s][2] |
[1]: https://app.circleci.com/pipelines/github/SetProtocol/set.js/494/workflows/43f7b984-626b-4f6f-a51c-de772b13b0df/jobs/903
[2]: …
=> Speed up CI

package.json, src/Set.ts, src/types/common.ts
These will use the same interfaces for the existing PerpV2LeverageModule/Viewer API classes.
For Basic data fetching related to vAsset positions/collateral token data and balances.
=> Add config options for BasisTradingModule/Viewer

package.json, src/Set.ts, src/api/DelegatedManagerFactoryAPI.ts, src/api/extensions/IssuanceExtensionAPI.ts, src/api/extensions/StreamingFeeExtensionAPI.ts, src/api/extensions/TradeExtensionAPI.ts, src/api/index.ts, src/assertions/SchemaAssertions.ts, src/types/common.ts, src/wrappers/set-protocol-v2/ContractWrapper.ts, src/wrappers/set-v2-strategies/ContractWrapper.ts, src/wrappers/set-v2-strategies/DelegatedManagerFactoryWrapper.ts, src/wrappers/set-v2-strategies/IssuanceExtensionWrapper.ts, src/wrappers/set-v2-strategies/StreamingFeeExtensionWrapper.ts, src/wrappers/set-v2-strategies/TradeExtensionWrapper.ts, test/api/DelegatedManagerFactoryAPI.spec.ts, test/api/extensions/IssuanceExtensionAPI.spec.ts, test/api/extensions/StreamingFeeExtensionAPI.spec.ts, test/api/extensions/TradeExtensionAPI.spec.ts, yarn.lock
Adds:
+ DelegatedManagerFactoryAPI
+ IssuanceExtensionAPI
+ TradeExtensionAPI
+ StreamingFeeExtensionAPI
Extensions are available on an `extensions` object exposed by the SetJS instance
```ts
setJS.extensions.tradeExtension.tradeForOperator(....)
```
**TODO**
+ is it possible to make set-protocol-v2 a dev-dependency at set-v2-strategies?
=> Add DelegatedManagerSystem API 

src/api/utils/tradeQuoter.ts
0x pinged us in telegram asking for this:
> Lawrence Forman, [Apr 7, 2022 at 8:50:28 AM]:
> Hey guys, are you guys using RFQ liquidity in your API requests?
> Actually, just to be safe, could you add excludedSources=RFQT until we update your ZeroExApiAdapter contract?
(Will need to publish this when merged, update the package at set-ui and push to production)
=> Exclude RFQT from ZeroEx sources [SIM-217]

package.json, src/api/utils/tradeQuoter.ts, test/fixtures/tradeQuote.ts
Changes to accomodate https://github.com/SetProtocol/set-protocol-v2/pull/241 which restores RFQT support
(`set-ui` consumes this adapter name and passes it as a parameter to TradeModule calls)
**Requires**
=> Update TradeQuoter to use `ZeroExApiAdapterV5` [SIM-230]
